#!/usr/bin/env bash

if [[ $1 == "status" ]]; then
	if [[ $(pamixer --default-source --get-mute) = "false" ]]; then
		echo yes
	else
		echo no
	fi
fi

if [[ $1 == "toggle" ]]; then
	pamixer --default-source -t
fi
