#!/usr/bin/env bash

xflux_status=$(/home/ramin/.config/eww/scripts/xflux_status)
state="$1"

if [[ "${state}" == "toggle" ]]; then
	if [[ "${xflux_status}" == true ]]; then
		pkill xflux
	else
		xflux -l 57.792506 -g 11.997145
	fi
fi

if [[ "${xflux_status}" == true ]]; then
	echo on
else
	echo off
fi
