#!/usr/bin/env bash

toggle=false

if [[ $1 == "toggle" ]]; then
	notify-send "button pressed"
	if [[ $toggle == true ]]; then
		toggle=false
		notify-send "Turn off"
		echo off
	else
		toggle=true
		notify-send "Turn on"
		echo on
	fi
fi
