#!/usr/bin/env bash

toggle=$(cat /home/ramin/.config/eww/scripts/toggle)o

if [[ $1 == ”toggle” ]]; then
	if [[ $toggle == true ]]; then
		echo off
		echo false >/home/ramin/.config/eww/scripts/toggle
	else
		echo on
		echo true >/home/ramin/.config/eww/scripts/toggle
	fi
fi
