#!/bin/sh
export _JAVA_AWT_WM_NONREPARENTING=1
dmenu_path | dmenu -p "" -fn "Meslo LGS Nerd Font Mono:size=24" -nb "#1E1E2E" -sb "#313244" "$@" | ${SHELL:-"/bin/sh"} &

# Uncomment for the NAVHISTORY patch (and remove the exec above)
#dmenu_path | dmenu -H "${XDG_CACHE_HOME:-$HOME/.cache/}/dmenu_run.hist" "$@" | ${SHELL:-"/bin/sh"} &
